In [ ]:
import numpy as np
#create an array with all one
my_array = np.ones(
    shape = (5 , 5)
)
print (my_array.dtype)
print (my_array)

float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#create an array with target value
target_value = np.full(
    shape = (4,4),
    fill_value= 10
)
print (target_value.dtype)
target_value

int64


array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
#create an identity matrix
id_matrix = np.eye( 4)
id_matrix
print(id_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#create an array with empty number
empty_num = np.empty(
    shape= (4,4)
)
print(empty_num)

[[5.e-323 5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323 5.e-323]]
