In [2]:
import numpy as np
# 0 dim array
dim_0 = np.array (40)


print ('value is:', dim_0, 'ndim', dim_0.ndim)



# 2 dim array

dim_1 = np.array(
 [   [2,4,5],
     [4,3,5],
    [3,6,4]] 

)

print('value is :', dim_1, 'ndim', dim_1.ndim)



# 3 dim array
dim_2 = np.array(
    [[[2,4,5],
     [4,3,5],
    [3,6,4]]]
)
print('value is :', dim_2, 'ndim', dim_2.ndim)

value is: 40 ndim 0
value is : [[2 4 5]
 [4 3 5]
 [3 6 4]] ndim 2
value is : [[[2 4 5]
  [4 3 5]
  [3 6 4]]] ndim 3


slicing numpy array

In [10]:
#slicing 1dim array
slice_1dim_array = np.array(
     [2,4,5,7,8]
)
print(slice_1dim_array[1:-1])

[4 5 7]


In [ ]:
#sliing 2dim array
slice_array = np.array(
     [[2,4,5,7,8],
      [4,3,5,8,5],
      [3,6,4,2,9,],
      [4,3,5,8,5]] 
#we need [3,5,8],[6,4,2]
)
print (slice_array[1:3,1:4])

[[3 5 8]
 [6 4 2]]
