type casting

In [2]:
#type casting
import numpy as np

type_casting = np.eye(4)
type_int = type_casting.astype(int)
print(type_casting)
print(type_casting.dtype)
print(type_int)
print(type_int.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
int64


create a sequential number 

In [3]:
seq_num = np.arange(
    start = 0,
    stop = 10,
    step = 2
)
print (seq_num)

[0 2 4 6 8]


# Basic usage of linspace to create an array from 0 to 100with 5 elements

In [4]:
lin_num = np.linspace(
    start = 0,
    stop = 100,
    num= 5
)
print (lin_num)

[  0.  25.  50.  75. 100.]


create a type of dimension array

In [8]:
# 0 dim array
dim_0 = np.array (40)
print ('value is:', dim_0, 'ndim', dim_0.ndim)

# 2 dim array
dim_1 = np.array(
 [   [2,4,5],
     [4,3,5],
    [3,6,4]]
)
print('value is :', dim_1, 'ndim', dim_1.ndim)


# 2 dim array
dim_2 = np.array(
    [[[2,4,5],
     [4,3,5],
    [3,6,4]]]
)
print('value is :', dim_2, 'ndim', dim_2.ndim)

value is: 40 ndim 0
value is : [[2 4 5]
 [4 3 5]
 [3 6 4]] ndim 2
value is : [[[2 4 5]
  [4 3 5]
  [3 6 4]]] ndim 3
