In [4]:
#type casting
import numpy as np

type_casting = np.eye(4)
type_int = type_casting.astype(int)
print(type_casting)
print(type_casting.dtype)
print(type_int)
print(type_int.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
int64
