type casting

In [5]:
#type casting
import numpy as np

type_casting = np.eye(4)
type_int = type_casting.astype(int)
print(type_casting)
print(type_casting.dtype)
print(type_int)
print(type_int.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
int64


create a sequential number 

In [8]:
seq_num = np.arange(
    start = 0,
    stop = 10,
    step = 2
)
print (seq_num)

[0 2 4 6 8]
